name: Cypress Tests

on:
  workflow_dispatch: 


jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    strategy:
      fail-fast: true
    steps:
      - name: Get Code 
        uses: actions/checkout@v2.7.0
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E tests
        continue-on-error: false
        run: node runner-electron.js
        
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}
      
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get Code 
        uses: actions/checkout@v2.7.0
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-chrome.js
    env:
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}
      TESULTS: ${{ secrets.TESULTS }}
      
  cypress-firefox-tests: 
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get Code 
        uses: actions/checkout@v2.7.0
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-firefox.js
    env:
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
      TESULTS: ${{ secrets.TESULTS }}
  
        
    
        
        
      
